In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel(r"C:\Users\DELL\BigDataProject\onlineretail\OnlineRetail.xlsx")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [5]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [7]:
products = df[['StockCode','Description','UnitPrice']]

products = products.drop_duplicates(subset='StockCode')

products.reset_index(drop=True,inplace=True)

products.head()

  StockCode                          Description  UnitPrice
0    85123A   WHITE HANGING HEART T-LIGHT HOLDER       2.55
1     71053                  WHITE METAL LANTERN       3.39
2    84406B       CREAM CUPID HEARTS COAT HANGER       2.75
3    84029G  KNITTED UNION FLAG HOT WATER BOTTLE       3.39
4    84029E       RED WOOLLY HOTTIE WHITE HEART.       3.39

In [8]:
products = products[
    products["StockCode"].astype(str).str.match(r'^[A-Za-z0-9]+$')
]

products = products.dropna(subset=["Description"])

products.head()

  StockCode                          Description  UnitPrice
0    85123A   WHITE HANGING HEART T-LIGHT HOLDER       2.55
1     71053                  WHITE METAL LANTERN       3.39
2    84406B       CREAM CUPID HEARTS COAT HANGER       2.75
3    84029G  KNITTED UNION FLAG HOT WATER BOTTLE       3.39
4    84029E       RED WOOLLY HOTTIE WHITE HEART.       3.39

In [10]:
import random

categories = [
    "Home Decor",
    "Kitchen",
    "Electronics",
    "Stationery",
    "Gift",
    "Garden",
    "Furniture",
    "Accessories"
]

products["category"] = [
    random.choice(categories)
    for _ in range(len(products))
]

In [11]:
products["supplier_id"] = [
    f"S{random.randint(1,100):03}"
    for _ in range(len(products))
]

In [12]:
products["lead_time_days"] = [
    random.randint(2,14)
    for _ in range(len(products))
]

In [13]:
products["cost_price"] = (
    products["UnitPrice"] * 0.65
).round(2)

products.rename(
    columns={
        "StockCode":"product_id",
        "Description":"product_name",
        "UnitPrice":"selling_price"
    },
    inplace=True
)

In [14]:
products.head()

,product_id,product_name,selling_price,category,supplier_id,lead_time_days,cost_price
0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,2.55,Gift,S056,10,1.66
1,71053,WHITE METAL LANTERN,3.39,Garden,S086,5,2.20
2,84406B,CREAM CUPID HEARTS COAT HANGER,2.75,Stationery,S085,12,1.79
3,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3.39,Stationery,S066,11,2.20
4,84029E,RED WOOLLY HOTTIE WHITE HEART.,3.39,Garden,S028,7,2.20

In [15]:
products.to_json(
    "products.json",
    orient="records",
    indent=4
)

In [17]:
inventory = products[["product_id"]].copy()

In [18]:
warehouses = ["W001","W002","W003"]

inventory["warehouse_id"] = [
    random.choice(warehouses)
    for _ in range(len(inventory))
]

In [19]:
inventory["current_stock"] = [
    random.randint(20,500)
    for _ in range(len(inventory))
]

In [20]:
inventory["reorder_point"] = [
    random.randint(30,80)
    for _ in range(len(inventory))
]

In [21]:
inventory["safety_stock"] = [
    random.randint(10,30)
    for _ in range(len(inventory))
]

In [22]:
inventory["last_updated"] = pd.Timestamp.today()

In [23]:
inventory.head()

,product_id,warehouse_id,current_stock,reorder_point,safety_stock,last_updated
0,85123A,W002,137,79,14,2026-06-30 20:00:49.794904
1,71053,W001,341,40,16,2026-06-30 20:00:49.794904
2,84406B,W002,246,58,28,2026-06-30 20:00:49.794904
3,84029G,W002,437,39,16,2026-06-30 20:00:49.794904
4,84029E,W002,289,47,24,2026-06-30 20:00:49.794904

In [24]:
inventory.to_csv(
    "inventory.csv",
    index=False
)